### ISSUE TITLE
why abandoned parrot

### ISSUE THREAD

**Issue by allyraza** [traduora/traduora#43]
hi there,

Nice project I am curious to know why you abandoned parrot, also why did you switch the api to node from go any particular reason 

Thank you for this awsome project!

**Comment by anthonynsimon** [comment]
Hey,

I initially built Parrot as a small project while learning Go, which eventually became much bigger than I had originally envisioned. This led to some choices that made developing new features slower than it should had been (i.e. the DB schemas we not well thought out and difficult to change).

I decided to do a rewrite and start a new project since it would have been a lot more difficult to provide an easy migration path for the users of Parrot and also in order to avoid some of my initial choices :)

The choice of Typescript this time is simply because I feel quite productive in it recently, so I would be able to focus more on the project's features. But it could have been any of Python/Scala/Go since that's what I'm familiar with at the moment and any would have done the job just fine.

Hope it answers your question!
