### ISSUE TITLE
Sensitive issues with uppercase and lowercase terms (mySQL)

### ISSUE THREAD

**Issue by LincWong** [traduora/traduora#81]
When importing a file, if the term contains case and space, the problem of term import failed will occur due to the problem of mySQL insensitive case and space.

example:
```
peterGood
```
```
petergood
```
An exception that already exists in the resource will be reported when importing, but in fact this is 2 different terms.

this is a very serious problem, I hope the author can pay attention to it. :(

**Comment by LincWong** [comment]
@anthonynsimon

**Comment by anthonynsimon** [comment]
Hi @LincWong  thanks for noticing this.

Currently terms are case-insensitive (two terms with the same characters regardless of case are considered the same), so the terms are considered to be duplicated. This is since some export formats are case insensitive as well for translation keys and it would have added more complexity to handle this from the start.

However, I can revisit the topic to see if we add support for this sometime in a future release.
