### ISSUE TITLE
update on support for PHP strings

### ISSUE THREAD

**Issue by phamdt** [traduora/traduora#82]
I see from the formats.md file that PHP strings is on the roadmap. I don't suppose you could give us a general estimate on when that will be worked on? e.g. "we're no longer prioritizing this" vs "sometime in 2020"

https://github.com/traduora/traduora/blob/be74b1b25e425121703130a26ab1c689123d839e/docs/concepts/formats.md

**Comment by anthonynsimon** [comment]
Unfortunately I haven’t had much time recently for this project but I can
possibly include this format on a release in the coming months.

It shouldn’t be too complicated and if you’re interested in contributing
let me know, I can give you a few pointers on how to implement this :)

**Comment by phamdt** [comment]
@anthonynsimon not sure when i could get to it, but yes, i would be curious about any pointers you have. if not me, perhaps someone else reading this issue could benefit from them.

**Comment by anthonynsimon** [comment]
@phamdt That's great! The changes made by this PR which added support for another format basically sum it up: https://github.com/traduora/traduora/pull/17/files

Essentially:
- Add some example file to the fixtures and write some tests describing the correct input/output.
- Add the parser and exporter for your format under `api/src/formatters/`
- Register the new format in the API inside the Import and the Export controllers, and also in the webapp so that it's aware of the new format.
- Update the changelog and documentation to mention your format.
